use $mysql_db;

BEGIN;
INSERT INTO `form_keys` VALUES
  (0, 'Account Age', 10, 'String', 0, 1, 0, 1)
, (0, 'Account location', 55, 'String', 0, 1, 0, 0)
, (0, 'Account Risk Category', 57, 'String', 0, 1, 0, 1)
, (0, 'Account Type', 50, 'String', 0, 1, 0, 1)
, (0, 'Account type exclusion', 50, 'String', 0, 1, 0, 0)
, (0, 'Address Near Border', 31, 'String', 0, 1, 0, 0)
, (0, 'Adverse News', 31, 'String', 0, 1, 0, 0)
, (0, 'Age', 12, 'String', 0, 1, 0, 0)
, (0, 'Balance Sheet Total', 11, 'String', 0, 1, 0, 0)
, (0, 'Bankrupt', 31, 'String', 0, 1, 0, 0)
, (0, 'Birth Location', 4, 'String', 0, 1, 0, 1)
, (0, 'Change in KYC details', 59, 'String', 0, 1, 0, 1)
, (0, 'Channel type', 54, 'String', 0, 1, 0, 0)
, (0, 'Citizenship Location Nationality', 4, 'String', 0, 1, 0, 1)
, (0, 'Complaint Submitted', 31, 'String', 0, 1, 0, 0)
, (0, 'Counterfeit or forged instruments', 31, 'String', 0, 1, 0, 0)
, (0, 'Customer or Counterparty', 9, 'String', 0, 1, 0, 0)
, (0, 'CUSTOMER SEGMENT', 7, 'String', 0, 1, 0, 1)
, (0, 'Deceased', 31, 'String', 0, 1, 0, 0)
, (0, 'Deviation From Historical Behaviour', 60, 'String', 0, 1, 1, 1)
, (0, 'Deviation from KYC profile', 62, 'String', 0, 1, 0, 1)
, (0, 'Domestic Trading Using Overseas Account', 31, 'String', 0, 1, 0, 0)
, (0, 'Domicile Location', 4, 'String', 0, 1, 0, 1)
, (0, 'Education Level', 14, 'String', 0, 1, 0, 0)
, (0, 'EMPLOYEE FLAG', 31, 'String', 0, 1, 0, 0)
, (0, 'Employment Status', 16, 'String', 0, 1, 0, 1)
, (0, 'Foreign Official', 31, 'String', 0, 1, 0, 0)
, (0, 'Gender', 17, 'String', 0, 1, 0, 0)
, (0, 'General Location', 4, 'String', 0, 1, 0, 1)
, (0, 'Group Of Individuals', 31, 'String', 0, 1, 0, 0)
, (0, 'High Risk Location', 31, 'String', 0, 1, 0, 0)
, (0, 'Home Ownership', 15, 'String', 0, 1, 0, 1)
, (0, 'Is PEP', 31, 'String', 0, 1, 0, 0)
, (0, 'Mailing to an unknown/unrelated address', 43, 'String', 0, 1, 0, 1)
, (0, 'Marital Status', 18, 'String', 0, 1, 0, 0)
, (0, 'Monthly Account Balance', 11, 'String', 0, 1, 0, 0)
, (0, 'Multiple accounts in multiple channels', 31, 'String', 0, 1, 0, 0)
, (0, 'Multiple users outside the Account location', 31, 'String', 0, 1, 0, 0)
, (0, 'Non Physical Address', 31, 'String', 0, 1, 0, 0)
, (0, 'Number Of Linked Accounts', 11, 'String', 0, 1, 0, 0)
, (0, 'Number Of Linked Customers', 11, 'String', 0, 1, 0, 0)
, (0, 'Operation Location', 4, 'String', 0, 1, 0, 1)
, (0, 'Party Corporate structure', 61, 'String', 0, 1, 0, 0)
, (0, 'PEP By Account Association', 31, 'String', 0, 1, 0, 0)
, (0, 'PEP On Watchlist', 31, 'String', 0, 1, 0, 0)
, (0, 'PEP relations', 58, 'String', 0, 1, 0, 1)
, (0, 'Profession', 19, 'String', 0, 1, 0, 1)
, (0, 'Purpose for account opening', 56, 'String', 0, 1, 0, 0)
, (0, 'RACE', 6, 'String', 0, 1, 0, 1)
, (0, 'Repeat Party Type', 31, 'String', 0, 1, 0, 0)
, (0, 'Residence Location', 4, 'String', 0, 1, 0, 1)
, (0, 'Risk Level', 11, 'String', 0, 1, 0, 0)
, (0, 'Sales Dominance', 31, 'String', 0, 1, 0, 0)
, (0, 'Single identity but multiple accounts', 31, 'String', 0, 1, 0, 0)
, (0, 'SPECIAL ATTENTION FLAG', 31, 'String', 0, 1, 0, 0)
, (0, 'Sudden Activity In An Inactive Account', 31, 'String', 0, 1, 0, 0)
, (0, 'Transaction Category', 2, 'String', 0, 1, 0, 1)
, (0, 'Transaction Characteristics', 42, 'String', 0, 1, 0, 1)
, (0, 'Transaction Direction', 41, 'String', 0, 1, 0, 1)
, (0, 'Transaction Recency', 21, 'String', 0, 1, 0, 1)
, (0, 'Multiple customers with same KYC information', 202, 'String', 0, 1, 0, 1)
, (1, 'Account Age', 10, 'String', 0, 1, 0, 0)
, (1, 'Account location', 55, 'String', 0, 1, 0, 0)
, (1, 'Account Risk Category', 57, 'String', 0, 1, 0, 1)
, (1, 'Account Type', 53, 'String', 0, 1, 0, 1)
, (1, 'Account type exclusion', 50, 'String', 0, 1, 0, 0)
, (1, 'Address Near Border', 31, 'String', 0, 1, 0, 0)
, (1, 'Adverse News', 31, 'String', 0, 1, 0, 0)
, (1, 'Adverse Organization', 31, 'String', 0, 1, 0, 0)
, (1, 'Annual Turnover', 11, 'String', 0, 1, 0, 0)
, (1, 'Balance Sheet Total', 11, 'String', 0, 1, 0, 0)
, (1, 'Bankrupt', 31, 'String', 0, 1, 0, 0)
, (1, 'BUSINESS PROFESSION', 27, 'String', 0, 1, 0, 1)
, (1, 'CASH INTENSIVE BUSINESS FLAG', 31, 'String', 0, 1, 0, 0)
, (1, 'Ceased Operation Flag', 31, 'String', 0, 1, 0, 0)
, (1, 'Change in KYC details', 59, 'String', 0, 1, 0, 1)
, (1, 'Channel type', 54, 'String', 0, 1, 0, 0)
, (1, 'COMPANY FORM', 25, 'String', 0, 1, 0, 1)
, (1, 'Complaint Submitted', 31, 'String', 0, 1, 0, 0)
, (1, 'CORRESPONDENT BANK FLAG', 31, 'String', 0, 1, 0, 0)
, (1, 'Counterfeit or forged instruments', 31, 'String', 0, 1, 0, 0)
, (1, 'Customer or Counterparty', 9, 'String', 0, 1, 0, 0)
, (1, 'Deviation From Historical Behaviour', 60, 'String', 0, 1, 1, 1)
, (1, 'Deviation from KYC profile', 62, 'String', 0, 1, 0, 1)
, (1, 'Entity type', 24, 'String', 0, 1, 0, 0)
, (1, 'Foreign Financial Org', 31, 'String', 0, 1, 0, 0)
, (1, 'General Location', 4, 'String', 0, 1, 0, 1)
, (1, 'Group Of Organizations', 31, 'String', 0, 1, 0, 0)
, (1, 'High Risk Location', 31, 'String', 0, 1, 0, 0)
, (1, 'Incorporated In Tax Haven', 31, 'String', 0, 1, 0, 0)
, (1, 'Incorporation Location', 4, 'String', 0, 1, 0, 1)
, (1, 'Industry', 5, 'String', 0, 1, 0, 0)
, (1, 'Is Business Legal', 31, 'String', 0, 1, 0, 0)
, (1, 'Is Offshore', 31, 'String', 0, 1, 0, 0)
, (1, 'Is PEP', 31, 'String', 0, 1, 0, 0)
, (1, 'Location of Authorised signatory/Directors', 55, 'String', 0, 1, 0, 0)
, (1, 'Location of Operation', 4, 'String', 0, 1, 0, 1)
, (1, 'Location of Origin', 4, 'String', 0, 1, 0, 1)
, (1, 'Major Buyer Location', 4, 'String', 0, 1, 0, 1)
, (1, 'Major Supplier Location', 4, 'String', 0, 1, 0, 1)
, (1, 'Major Vendor Location', 4, 'String', 0, 1, 0, 1)
, (1, 'MONEY SERVICE BUREAU FLAG', 31, 'String', 0, 1, 0, 0)
, (1, 'Monthly Account Balance', 11, 'String', 0, 1, 0, 0)
, (1, 'Multiple accounts in multiple channels', 31, 'String', 0, 1, 0, 0)
, (1, 'Multiple users outside the Account location', 31, 'String', 0, 1, 0, 0)
, (1, 'NATURE OF BUSINESS', 23, 'String', 0, 1, 0, 1)
, (1, 'NGO', 31, 'String', 0, 1, 0, 0)
, (1, 'Non Bank Finance Institute', 31, 'String', 0, 1, 0, 0)
, (1, 'Non Physical Address', 31, 'String', 0, 1, 0, 0)
, (1, 'Number Of Linked Accounts', 11, 'String', 0, 1, 0, 0)
, (1, 'Number Of Linked Customers', 11, 'String', 0, 1, 0, 0)
, (1, 'Operation Location', 4, 'String', 0, 1, 0, 1)
, (1, 'Organization Age', 26, 'String', 0, 1, 0, 0)
, (1, 'Paid up capital', 11, 'String', 0, 1, 0, 0)
, (1, 'Party Corporate structure', 61, 'String', 0, 1, 0, 0)
, (1, 'PEP By Account Association', 31, 'String', 0, 1, 0, 0)
, (1, 'PEP On Watchlist', 31, 'String', 0, 1, 0, 0)
, (1, 'PEP relations', 58, 'String', 0, 1, 0, 1)
, (1, 'Purpose for account opening', 56, 'String', 0, 1, 0, 0)
, (1, 'Registered/mailing address is same as the FA/PO box address ', 31, 'String', 0, 1, 0, 0)
, (1, 'Repeat Party Type', 31, 'String', 0, 1, 0, 0)
, (1, 'Risk Level', 11, 'String', 0, 1, 0, 0)
, (1, 'Sales Dominance', 31, 'String', 0, 1, 0, 0)
, (1, 'Single identity but multiple accounts', 31, 'String', 0, 1, 0, 0)
, (1, 'SPECIAL ATTENTION FLAG', 31, 'String', 0, 1, 0, 0)
, (1, 'Sudden Activity In An Inactive Account', 31, 'String', 0, 1, 0, 0)
, (1, 'Transaction Category', 2, 'String', 0, 1, 0, 1)
, (1, 'Transaction Characteristics', 42, 'String', 0, 1, 0, 1)
, (1, 'Transaction Direction', 41, 'String', 0, 1, 0, 1)
, (1, 'Transaction Recency', 21, 'String', 0, 1, 0, 1)
, (1, 'WEAK AML CTRL FLAG', 31, 'String', 0, 1, 0, 0)
, (1, 'WHOLESALE BANKNOTE FLAG', 31, 'String', 0, 1, 0, 0)
, (2, 'Base Currency for Transaction', 7, 'String', 0, 1, 0, 0)
, (2, 'Cash Transactions In Excess Of Trade Limit', 11, 'String', 0, 1, 0, 0)
, (2, 'Circular Transactions Present', 31, 'String', 0, 1, 0, 0)
, (2, 'Deviation From Historical Behaviour', 60, 'String', 0, 1, 1, 1)
, (2, 'Domestic Transactions Frequency', 11, 'String', 0, 1, 0, 0)
, (2, 'Frequency of Incoming Cash Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Frequency of Incoming Transactions from Tax Haven', 11, 'String', 0, 1, 0, 0)
, (2, 'Frequency of Outgoing Cash Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Frequency of Outgoing Transactions to Tax Haven', 11, 'String', 0, 1, 0, 0)
, (2, 'Gaps In Consecutive Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'High Volume Incoming and Outgoing Transactions In Short Period', 31, 'String', 0, 1, 0, 0)
, (2, 'Incoming Cash Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Incoming Payment', 11, 'String', 0, 1, 0, 0)
, (2, 'Incoming Transaction Value', 11, 'String', 0, 1, 0, 0)
, (2, 'Incoming Transactions Frequency', 11, 'String', 0, 1, 0, 0)
, (2, 'Loss or Gain in Trade', 11, 'String', 0, 1, 0, 0)
, (2, 'Lumpsum Repayment of Credit Card Balance', 31, 'String', 0, 1, 0, 0)
, (2, 'Multiple Outgoing Overseas Transactions', 31, 'String', 0, 1, 0, 0)
, (2, 'Multiple Transactions of Similar Amounts', 31, 'String', 0, 1, 0, 0)
, (2, 'Outgoing Cash Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Outgoing Payment', 11, 'String', 0, 1, 0, 0)
, (2, 'Outgoing Transaction Value', 11, 'String', 0, 1, 0, 0)
, (2, 'Outgoing Transactions Frequency', 11, 'String', 0, 1, 0, 0)
, (2, 'Overseas Transaction Incoming Frequency', 11, 'String', 0, 1, 0, 0)
, (2, 'Percent of Incoming Transferred', 11, 'String', 0, 1, 0, 0)
, (2, 'Purchase to Sell Value', 11, 'String', 0, 1, 0, 0)
, (2, 'Purpose Code for Transactions', 33, 'String', 0, 1, 0, 0)
, (2, 'Quick Withdrawal Of Funds', 31, 'String', 0, 1, 0, 0)
, (2, 'Selling With Minimum Loss/Gain', 31, 'String', 0, 1, 0, 0)
, (2, 'Single Identity But Multiple Accounts And Multiple Names', 31, 'String', 0, 1, 0, 0)
, (2, 'Sudden Surge of Transactions', 31, 'String', 0, 1, 0, 0)
, (2, 'Sudden Surge Of Withdrawal', 11, 'String', 0, 1, 0, 0)
, (2, 'Sum of Incoming Cash Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Sum Of Incoming Transaction is Higher Than Income', 31, 'String', 0, 1, 0, 0)
, (2, 'Sum Of Incoming Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Sum of Outgoing Cash Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Sum Of Outgoing Transaction is Higher Than Income', 31, 'String', 0, 1, 0, 0)
, (2, 'Sum Of Outgoing Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Total amount of stocks purchased', 11, 'String', 0, 1, 0, 0)
, (2, 'Trading Limit or Income Level Breach', 31, 'String', 0, 1, 0, 0)
, (2, 'Trading Transaction from Different Location', 31, 'String', 0, 1, 0, 0)
, (2, 'Transaction Below Threshold', 31, 'String', 0, 1, 0, 0)
, (2, 'Transaction Commission', 31, 'String', 0, 1, 0, 0)
, (2, 'Transaction Directed to High Terrorism Countries', 31, 'String', 0, 1, 0, 0)
, (2, 'Transaction Direction', 8, 'String', 0, 1, 0, 1)
, (2, 'Transaction Frequency', 11, 'String', 0, 1, 0, 0)
, (2, 'Transaction Genuity', 28, 'String', 0, 1, 0, 0)
, (2, 'Transaction Instrument', 22, 'String', 0, 1, 0, 1)
, (2, 'Transaction Place', 29, 'String', 0, 1, 0, 0)
, (2, 'Transaction Purpose Defined', 31, 'String', 0, 1, 0, 0)
, (2, 'Transaction Recency', 21, 'String', 0, 1, 0, 1)
, (2, 'Transaction Type Category', 30, 'String', 0, 1, 0, 0)
, (2, 'Transaction Value', 11, 'String', 0, 1, 0, 0)
, (2, 'Transaction Volume', 11, 'String', 0, 1, 0, 0)
, (2, 'Transactions Back To Origin Location', 11, 'String', 0, 1, 0, 0)
, (2, 'Transactions Directed Towards Tax Haven Countries', 31, 'String', 0, 1, 0, 0)
, (2, 'Transactions Towards Buying/selling Penny Stocks', 11, 'String', 0, 1, 0, 0)
, (2, 'Transactions Towards Faster Repayment Of Loans', 31, 'String', 0, 1, 0, 0)
, (2, 'Volume of Cheques For Family Member', 11, 'String', 0, 1, 0, 0)
, (2, 'Volume of Outgoing Transactions To Tax Havens', 11, 'String', 0, 1, 0, 0)
, (2, 'Volume Of Overseas Transactions', 11, 'String', 0, 1, 0, 0)
, (2, 'Voucher Consumption Frequency', 11, 'String', 0, 1, 0, 0)
, (2, 'Voucher Consumption Value', 11, 'String', 0, 1, 0, 0)
, (4, 'Account Location', 4, 'String', 0, 1, 0, 0)
, (4, 'Relationship between Parties', 34, 'String', 0, 1, 0, 1)
, (4, 'Similarity between Parties', 35, 'String', 0, 1, 0, 0)
, (5, 'Account Location', 4, 'String', 0, 1, 0, 0)
, (5, 'Relationship between Parties', 37, 'String', 0, 1, 0, 1)
, (5, 'Similarity between Parties', 39, 'String', 0, 1, 0, 0)
, (6, 'Account Location', 4, 'String', 0, 1, 0, 0)
, (6, 'Relationship between Parties', 36, 'String', 0, 1, 0, 0)
, (6, 'Similarity between Parties', 39, 'String', 0, 1, 0, 0);

INSERT INTO `group_values` VALUES
  (1, 'Accumulating Funds')
, (1, 'Any')
, (1, 'Card / Loan Repayment')
, (1, 'Circulation of Funds')
, (1, 'Dispersion of Funds')
, (1, 'Exceeding Bank Threshold Limits')
, (1, 'Flow Through of Funds')
, (1, 'Forged Instruments')
, (1, 'Frequent Amendments to Customer Profile')
, (1, 'Frequent Transactions')
, (1, 'Frequent Transactions between Similar Entities')
, (1, 'Frequent Transactions between unrelated parties')
, (1, 'Fund Transfer Between Corporate Account & Individual Account')
, (1, 'Fund Transfer with High Risk Countries')
, (1, 'Fund Transfer with High Risk Entities')
, (1, 'Funds from Unknown Sources')
, (1, 'High velocity of funds')
, (1, 'Historical Suspicious Report')
, (1, 'Immediate withdrawal after deposit')
, (1, 'Large Cash Transaction')
, (1, 'Laundering via Shell Companies')
, (1, 'Layering of Funds')
, (1, 'Money Muling')
, (1, 'Multiple Users Using Single Account')
, (1, 'Negative Tax Reports')
, (1, 'Regular Similar Transactions')
, (1, 'Remittance Transactions')
, (1, 'Structured Transactions')
, (1, 'Transactions Exceeding Customer Income')
, (1, 'Transactions Involving Different Businesses')
, (1, 'Unusual Transactional Activities')
, (1, 'Usage of Dormant Accounts')
, (1, 'Usage of UBO')
, (2, 'Any')
, (2, 'ATM Transactions')
, (2, 'Card Payments')
, (2, 'Card Transactions')
, (2, 'Cash Transactions')
, (2, 'Cash-Equivalent Transactions')
, (2, 'Cheque Transactions')
, (2, 'E-Wallet Transactions')
, (2, 'Fund Transfers')
, (2, 'High Risk Transactions')
, (2, 'Loan Payments')
, (2, 'Overseas Fund Transfers')
, (2, 'Voucher')
, (3, 'Any')
, (3, 'Suspected corruption and bribery')
, (3, 'Suspected counterfeiting and piracy of products')
, (3, 'Suspected counterfeiting currency')
, (3, 'Suspected environmental crime')
, (3, 'Suspected extortion')
, (3, 'Suspected forgery')
, (3, 'Suspected fraud')
, (3, 'Suspected illicit arms trafficking')
, (3, 'Suspected illicit trafficking in narcotic drugs and psychotropic substances')
, (3, 'Suspected illicit trafficking in stolen and other goods')
, (3, 'Suspected insider trading and market manipulation')
, (3, 'Suspected kidnapping, illegal restraint and hostage-taking')
, (3, 'Suspected murder, grievous bodily injury')
, (3, 'Suspected participation in an organised criminal group and racketeering')
, (3, 'Suspected piracy')
, (3, 'Suspected robbery or theft')
, (3, 'Suspected sexual exploitation, including sexual exploitation of children')
, (3, 'Suspected smuggling (including in relation to customs and excise duties and taxes)')
, (3, 'Suspected tax crimes (related to direct taxes and indirect taxes)')
, (3, 'Suspected terrorism, including terrorist financing')
, (3, 'Suspected trafficking in human beings and migrant smuggling')
, (4, 'Afghanistan')
, (4, 'Albania')
, (4, 'Algeria')
, (4, 'AMER North Central And South America')
, (4, 'Andorra')
, (4, 'ANG Ola')
, (4, 'Antigua And Barbuda')
, (4, 'Any')
, (4, 'APAC Asia Pacific')
, (4, 'Argentina')
, (4, 'Armenia')
, (4, 'Australia')
, (4, 'Austria')
, (4, 'Azerbaijan')
, (4, 'Bahrain')
, (4, 'Bangladesh')
, (4, 'Barbados')
, (4, 'Belarus')
, (4, 'Belgium')
, (4, 'Belize')
, (4, 'Benin')
, (4, 'Bhutan')
, (4, 'Bolivia')
, (4, 'Bosnia And Herzegovina')
, (4, 'Botswana')
, (4, 'Brazil')
, (4, 'Brunei')
, (4, 'Bulgaria')
, (4, 'Burkina Faso')
, (4, 'Burundi')
, (4, 'Cambodia')
, (4, 'Cameroon')
, (4, 'Canada')
, (4, 'Cape Verde')
, (4, 'Central African Republic')
, (4, 'Chad')
, (4, 'Chile')
, (4, 'China')
, (4, 'Co NGO Democratic Republic Of The')
, (4, 'Co NGO Republic Of The')
, (4, 'Colombia')
, (4, 'Comoros')
, (4, 'Costa Rica')
, (4, 'Cote D Ivoire')
, (4, 'Croatia')
, (4, 'Cuba')
, (4, 'Cyprus')
, (4, 'Czech Republic')
, (4, 'Denmark')
, (4, 'Different')
, (4, 'Djibouti')
, (4, 'Dominica')
, (4, 'Dominican Republic')
, (4, 'East Timor Timor Leste')
, (4, 'Ecuador')
, (4, 'Egypt')
, (4, 'El Salvador')
, (4, 'EMEA Europe Middle East And Africa')
, (4, 'Equatorial Guinea')
, (4, 'Eritrea')
, (4, 'Estonia')
, (4, 'Ethiopia')
, (4, 'EU European Union')
, (4, 'Fiji')
, (4, 'Finland')
, (4, 'France')
, (4, 'Gabon')
, (4, 'Georgia')
, (4, 'Germany')
, (4, 'Ghana')
, (4, 'Global')
, (4, 'Greece')
, (4, 'Grenada')
, (4, 'Guatemala')
, (4, 'Guinea')
, (4, 'Guinea Bissau')
, (4, 'Guyana')
, (4, 'Haiti')
, (4, 'Honduras')
, (4, 'Hungary')
, (4, 'Iceland')
, (4, 'India')
, (4, 'Indonesia')
, (4, 'Iran')
, (4, 'Iraq')
, (4, 'Ireland')
, (4, 'Israel')
, (4, 'Italy')
, (4, 'Jamaica')
, (4, 'Japan')
, (4, 'Jordan')
, (4, 'Kazakhstan')
, (4, 'Kenya')
, (4, 'Kiribati')
, (4, 'Kosovo')
, (4, 'Kuwait')
, (4, 'Kyrgyzstan')
, (4, 'LAD Latin America Division')
, (4, 'Laos')
, (4, 'Latvia')
, (4, 'Lebanon')
, (4, 'Lesotho')
, (4, 'Liberia')
, (4, 'Libya')
, (4, 'Liechtenstein')
, (4, 'Lithuania')
, (4, 'Luxembourg')
, (4, 'Macedonia')
, (4, 'Madagascar')
, (4, 'Malawi')
, (4, 'Malaysia')
, (4, 'Maldives')
, (4, 'Mali')
, (4, 'Malta')
, (4, 'Marshall Islands')
, (4, 'Mauritania')
, (4, 'Mauritius')
, (4, 'Mexico')
, (4, 'Micronesia Federated States Of')
, (4, 'Mo NG Olia')
, (4, 'Moldova')
, (4, 'Monaco')
, (4, 'Montenegro')
, (4, 'Morocco')
, (4, 'Mozambique')
, (4, 'Myanmar Burma')
, (4, 'NA North America')
, (4, 'Namibia')
, (4, 'Nauru')
, (4, 'Nepal')
, (4, 'Netherlands')
, (4, 'New Zealand')
, (4, 'Nicaragua')
, (4, 'Niger')
, (4, 'Nigeria')
, (4, 'North Korea')
, (4, 'Norway')
, (4, 'Oman')
, (4, 'Pakistan')
, (4, 'Palau')
, (4, 'Panama')
, (4, 'Papua New Guinea')
, (4, 'Paraguay')
, (4, 'Peru')
, (4, 'Philippines')
, (4, 'Poland')
, (4, 'Portugal')
, (4, 'Qatar')
, (4, 'Romania')
, (4, 'Russia')
, (4, 'Rwanda')
, (4, 'Saint Kitts And Nevis')
, (4, 'Saint Lucia')
, (4, 'Saint Vincent And The Grenadines')
, (4, 'Same')
, (4, 'Samoa')
, (4, 'San Marino')
, (4, 'Sao Tome And Principe')
, (4, 'Saudi Arabia')
, (4, 'Senegal')
, (4, 'Serbia')
, (4, 'Seychelles')
, (4, 'Sierra Leone')
, (4, 'Singapore')
, (4, 'Slovakia')
, (4, 'Slovenia')
, (4, 'Solomon Islands')
, (4, 'Somalia')
, (4, 'South Africa')
, (4, 'South Korea')
, (4, 'South Sudan')
, (4, 'Spain')
, (4, 'Sri Lanka')
, (4, 'Sudan')
, (4, 'Suriname')
, (4, 'Swaziland')
, (4, 'Sweden')
, (4, 'Switzerland')
, (4, 'Syria')
, (4, 'Taiwan')
, (4, 'Tajikistan')
, (4, 'Tanzania')
, (4, 'Thailand')
, (4, 'The Bahamas')
, (4, 'The Gambia')
, (4, 'Togo')
, (4, 'Tonga')
, (4, 'Trinidad And Tobago')
, (4, 'Tunisia')
, (4, 'Turkey')
, (4, 'Turkmenistan')
, (4, 'Tuvalu')
, (4, 'Uganda')
, (4, 'Ukraine')
, (4, 'United Arab Emirates')
, (4, 'United Kingdom')
, (4, 'United States Of America')
, (4, 'Uruguay')
, (4, 'Uzbekistan')
, (4, 'Vanuatu')
, (4, 'Vatican City Holy See')
, (4, 'Venezuela')
, (4, 'Vietnam')
, (4, 'Yemen')
, (4, 'Zambia')
, (4, 'Zimbabwe')
, (5, 'Any')
, (5, 'Cash Intensive')
, (5, 'Cash Trading')
, (5, 'Drugs')
, (5, 'Finance')
, (5, 'Food')
, (5, 'Human Resource')
, (5, 'Insurance Job')
, (5, 'IT')
, (5, 'Manufacturing')
, (5, 'Pharmacy')
, (5, 'Phone Accessories')
, (5, 'Real Estate')
, (5, 'Retailer')
, (5, 'Services')
, (5, 'Shopkeeper')
, (5, 'Trading')
, (5, 'Wholesaler')
, (6, 'Any')
, (6, 'Chinese')
, (6, 'Eurasian')
, (6, 'Indian')
, (6, 'Malay')
, (6, 'Others')
, (7, 'Business Banking')
, (7, 'Commercial Banking')
, (7, 'Corporate Banking Overseas')
, (7, 'Corporate Banking Regional')
, (7, 'Corporate Banking Singapore')
, (7, 'Financial Institutional Group')
, (7, 'Global Treasury')
, (7, 'Government Linked Co')
, (7, 'Multi National Corp')
, (7, 'PFS Mass')
, (7, 'Private Banking')
, (7, 'Priviledge Banking')
, (7, 'Priviledge Reserve')
, (7, 'Shareholders Fund')
, (7, 'Staff Loans')
, (7, 'Wealth Banking')
, (8, 'Any')
, (8, 'Both Ways')
, (8, 'Counterparty to Counterparty')
, (8, 'Counterparty to Customer')
, (8, 'Customer to Counterparty')
, (8, 'Customer to Customer')
, (9, 'Any')
, (9, 'Counterparty')
, (9, 'Customer')
, (10, '1 to 3 years')
, (10, '3 to 5 years')
, (10, '5 to 10 years')
, (10, 'Any')
, (10, 'Less than 1 year')
, (10, 'More than 10 years')
, (11, 'Any')
, (11, 'High')
, (11, 'Low')
, (11, 'Medium')
, (11, 'None')
, (12, '15 to 18 years old')
, (12, '18 to 25 years old')
, (12, '25 to 35 years old')
, (12, '35 to 45 years old')
, (12, '45 to 55 years old')
, (12, '55 to 65 years old')
, (12, 'Any')
, (12, 'Below 15 years old')
, (12, 'More than 65 years old')
, (14, 'Any')
, (14, 'Post Secondary Vocational/')
, (14, 'Primary')
, (14, 'Secondary')
, (14, 'Technical University')
, (14, 'Tertiary Post-graduate')
, (15, 'Any')
, (15, 'Company residence')
, (15, 'Fully owned')
, (15, 'Living with Parents')
, (15, 'Loan/Mortgaged')
, (15, 'Renting')
, (16, 'Any')
, (16, 'Employed')
, (16, 'Full Time')
, (16, 'Part Time')
, (16, 'Retired')
, (16, 'Self Employed (Business Owner)')
, (16, 'Self Employed (Sole Proprietor/Freelance)')
, (16, 'Unemployed')
, (17, 'Any')
, (17, 'Female')
, (17, 'Male')
, (17, 'Others/Non-Binary')
, (18, 'Any')
, (18, 'Divorced')
, (18, 'Married')
, (18, 'Single')
, (18, 'Widowed')
, (19, 'Agriculture, Food and Natural Resources. Architecture and Construction.')
, (19, 'Any')
, (19, 'Arts, Audio/Video Technology and Communications')
, (19, 'Business')
, (19, 'Education and Training')
, (19, 'Engineering and Mathematics')
, (19, 'Finance')
, (19, 'Government and Public Administration')
, (19, 'Health Care/Medicine')
, (19, 'Hospitality and Tourism')
, (19, 'Industrial and Manufacturing')
, (19, 'Law Enforcement and Armed Forces')
, (19, 'Student')
, (19, 'Technology/Science')
, (21, 'Any')
, (21, 'Last 1 yr')
, (21, 'Last 10 yrs')
, (21, 'Last 2 yrs')
, (21, 'Last 24 hrs')
, (21, 'Last 3 months')
, (21, 'Last 30 days')
, (21, 'Last 5 yrs')
, (21, 'Last 6 months')
, (21, 'Last 7 days')
, (22, 'ACH')
, (22, 'Any')
, (22, 'Any instrument')
, (22, 'Any Other Instrument')
, (22, 'Any Type of Card')
, (22, 'ATM')
, (22, 'Bonds')
, (22, 'Cards')
, (22, 'Cash')
, (22, 'Cashier Order')
, (22, 'Credit Card')
, (22, 'Cryptocurrency')
, (22, 'Debit Card')
, (22, 'Demand Draft')
, (22, 'EFT')
, (22, 'Exchange Traded Funds')
, (22, 'Gaming Instruments')
, (22, 'Government Grant/Payouts')
, (22, 'Letter of Credit')
, (22, 'Precious Stones and Metals')
, (22, 'Prepaid Card')
, (22, 'Property or Real Estate')
, (22, 'Securities')
, (22, 'Stocks & Shares')
, (22, 'SWIFT')
, (22, 'Voucher')
, (22, 'Wire Transfer')
, (23, 'Advertising activities')
, (23, 'Any')
, (23, 'Corporate training services and motivational course providers')
, (23, 'Development of other software and programming activities n.e.c.')
, (23, 'Management consultancy services (general)')
, (23, 'Management consultancy services n.e.c.')
, (23, 'Other holding companies')
, (23, 'Other information technology and computer service activities')
, (23, 'Retail sale via internet (with income mainly from online sales)')
, (23, 'Wholesale trade of a variety of goods without a dominant product')
, (24, 'Any')
, (24, 'Clubs')
, (24, 'Government')
, (24, 'Individual')
, (24, 'Partnerships and unincorporated bodies')
, (24, 'Private limited')
, (24, 'Public')
, (24, 'Public sector bodies')
, (24, 'Societies and Charities')
, (24, 'Sole proprietorships')
, (24, 'State-owned companies and supranationals')
, (24, 'Trust')
, (25, 'Any')
, (25, 'Association/ Clubs / Society / Co-op')
, (25, 'LLP')
, (25, 'Others (Please specify)')
, (25, 'Partnership/Limited Partnership')
, (25, 'Private Ltd')
, (25, 'Public Ltd. Co. (Listed Locally)')
, (25, 'Public Ltd. Co. (Listed Overseas)')
, (25, 'Sole Proprietorship')
, (26, '1 to 5 years')
, (26, '10 to 20 years')
, (26, '20 to 40 years')
, (26, '40 to 60 years')
, (26, '5 to 10 years')
, (26, 'Any')
, (26, 'Less than 1 year')
, (26, 'More than 60 years')
, (27, 'Any')
, (27, 'B2B and Finance')
, (27, 'Construction/Real Estate')
, (27, 'Consulting')
, (27, 'Education and Childcare')
, (27, 'Food and Beverage')
, (27, 'General Services')
, (27, 'Health and Beauty')
, (27, 'Holding companies')
, (27, 'Miscellaneous')
, (27, 'Retail')
, (27, 'Shipping and Logistics')
, (27, 'Wholesale')
, (28, 'Any')
, (28, 'Fraud')
, (28, 'Genuine')
, (28, 'Hacked')
, (29, 'Any')
, (29, 'ATM')
, (29, 'Bank Branch')
, (29, 'Mobile')
, (29, 'Online')
, (29, 'Post Office')
, (29, 'Store')
, (30, 'Any')
, (30, 'Crypto Fund Transfer')
, (30, 'Local Fund Transfer')
, (30, 'Local or Overseas')
, (30, 'Overseas Fund Transfer')
, (31, 'Any')
, (31, 'No')
, (31, 'Yes')
, (32, 'Broker/Dealer')
, (32, 'Commercial/Wholesale Banking')
, (32, 'Correspondent Banking')
, (32, 'Fintechs/Neo-banks/NPMs')
, (32, 'Private/Wealth Management')
, (32, 'Retail/Retail Banking')
, (33, 'Any')
, (33, 'Crypto Exchanges')
, (33, 'Merchant Payment')
, (33, 'Non Profit Donations')
, (33, 'Religious Donations')
, (34, 'Any')
, (34, 'Friends')
, (34, 'Goods received')
, (34, 'Goods sent')
, (34, 'Parent - Child')
, (34, 'Relatives')
, (34, 'Self')
, (34, 'Spouse')
, (34, 'Unrelated')
, (35, 'Address')
, (35, 'Any')
, (35, 'City')
, (35, 'Club or Hobby')
, (35, 'Common Counter-party')
, (35, 'Contact Number')
, (35, 'Location')
, (35, 'Name')
, (35, 'Political Party')
, (35, 'Religion')
, (35, 'Zip Code')
, (36, 'Any')
, (36, 'Branch')
, (36, 'Client')
, (36, 'Director')
, (36, 'Employment')
, (36, 'Head Office')
, (36, 'Same Beneficial Owner')
, (36, 'Self')
, (36, 'Shareholder')
, (36, 'Sister Organization')
, (36, 'Unrelated')
, (37, 'Any')
, (37, 'Director')
, (37, 'Employment')
, (37, 'Goods received')
, (37, 'Goods sent')
, (37, 'Same Beneficial Owner')
, (37, 'Self')
, (37, 'Shareholder')
, (37, 'Unrelated')
, (38, 'Any')
, (38, 'Crypto Exchanges')
, (38, 'Merchant Payment')
, (38, 'Non Profit Donations')
, (38, 'Religious Donations')
, (39, 'Address')
, (39, 'Any')
, (39, 'Bank Account')
, (39, 'City')
, (39, 'Common Counter-party')
, (39, 'Contact Number')
, (39, 'Location')
, (39, 'Name')
, (39, 'Same Supplier/Vendor')
, (39, 'Zip code')
, (41, 'Any')
, (41, 'Incoming')
, (41, 'Outgoing')
, (42, 'Accounts Maintained by Trustees')
, (42, 'Any')
, (42, 'Between Corporate and Individual')
, (42, 'Credit and debit transactions of similar amount')
, (42, 'Customer and its Related Entities')
, (42, 'Different Business')
, (42, 'Different Currencies')
, (42, 'Distinct Customers')
, (42, 'Funds from Related Party')
, (42, 'Funds from Unrelated Party')
, (42, 'High Risk Countries')
, (42, 'High Risk Entities')
, (42, 'High Transaction Flow Through')
, (42, 'Large cash advance refunds or other refunds')
, (42, 'Multi Branches')
, (42, 'Multiple Trustee of an Account')
, (42, 'No Transaction Purpose or Source of Funds Information')
, (42, 'Offshore Company')
, (42, 'Outgoing cash transactions')
, (42, 'Over Customer Income')
, (42, 'Overseas')
, (42, 'Shell Company')
, (42, 'Tax Haven Countries')
, (42, 'Transaction patterns not in line with Principal business')
, (42, 'Transfer across multiple related accounts')
, (42, 'Young Age')
, (43, 'Financial information')
, (43, 'Financial instruction')
, (43, 'Financial instrument')
, (50, 'Any')
, (50, 'Cash Trading Account')
, (50, 'Checking')
, (50, 'Fixed Deposits')
, (50, 'Merchant')
, (50, 'Private')
, (50, 'Privilege')
, (50, 'Savings And Current')
, (50, 'Trading')
, (53, 'Any')
, (53, 'CASA')
, (53, 'Cash Trading Account')
, (53, 'Corporate')
, (53, 'Fixed Deposits')
, (53, 'Merchant Business')
, (53, 'Trading')
, (54, 'Others')
, (54, 'PSP')
, (55, 'Any')
, (55, 'Local')
, (55, 'Overseas')
, (56, 'Known')
, (56, 'Unknown')
, (57, 'New account')
, (57, 'New Relationship')
, (57, 'PEP')
, (57, 'STR')
, (58, 'Executive')
, (58, 'PPTA')
, (58, 'UBO')
, (59, 'Authorised signatory')
, (59, 'Beneficiary ownership')
, (59, 'Mailing address')
, (59, 'Name')
, (59, 'Registration number')
, (59, 'Verification number')
, (60, 'Annual Turnover')
, (60, 'Deviation based on Merchant Activity / Behaviour')
, (60, 'Deviation from peers')
, (60, 'Deviation from self')
, (60, 'Income')
, (60, 'Monthly Account Balance')
, (60, 'Voucher Consumption Rate')
, (61, 'Any other payment service provider or payment aggregator')
, (61, 'Client majority-owned merchant (>50%)')
, (61, 'Client wholly-owned merchant')
, (61, 'Payment service provider or payment aggregator which is registered FATF member country and holding relevant licence')
, (61, 'Redeem code reseller')
, (61, 'Telecommunication')
, (61, 'Third-party merchant')
, (62, 'Originator bank name/SWIFT code')
, (62, 'Originator name')
, (62, 'Payment amount')
, (62, 'Payment Frequency')
, (62, 'Registered bank account')
, (62, 'Registered users')
, (155, 'Any')
, (155, 'Change/Deviation in Profile')
, (155, 'Other')
, (155, 'Other Abnormal Risky Transaction Types')
, (155, 'Tax Crimes Related Transactions')
, (155, 'Trade Related Transactions')
, (155, 'Transactions Involving Accounts of the Customer with the Payment Service Provider')
, (155, 'Transactions Involving Large Amounts of Cash')
, (155, 'Transactions Involving Unidentified Parties')
, (155, 'Transactions Which Do Not Make Economic Sense')
, (166, 'Any')
, (166, 'Any instrument')
, (166, 'Any Other Instrument')
, (166, 'ATM')
, (166, 'Bill payment')
, (166, 'Bonds')
, (166, 'Cards')
, (166, 'Cash')
, (166, 'Cashier Order')
, (166, 'Cheque')
, (166, 'Credit Card')
, (166, 'Cryptocurrency')
, (166, 'Debit Card')
, (166, 'Demand Draft')
, (166, 'EFT')
, (166, 'Ewallet')
, (166, 'Exchange Traded Funds')
, (166, 'Gaming Instruments')
, (166, 'Government Grant/Payouts')
, (166, 'Letter of Credit')
, (166, 'Loan')
, (166, 'Mortgage-Backed Security (MBS)')
, (166, 'Precious Stones and Metals')
, (166, 'Prepaid Card')
, (166, 'Property or Real Estate')
, (166, 'Securities')
, (166, 'Stocks & Shares')
, (166, 'SWIFT')
, (166, 'Voucher')
, (166, 'Wire Transfer')
, (202, 'ID number')
, (202, 'Residential Address')
, (202, 'Phone number')
, (202, 'Authorized Signatory')
, (202, 'Mailing Address');
;

INSERT IGNORE group_values(group_code,`value`) VALUES
(201, 'Savings Account'),
(201, 'Debit Card'),
(201, 'Credit Card'),
(201, 'Pre-paid / Gift Card'),
(201, 'Loans'),
(201, 'Investments / Deposits'),
(201, 'Insurance'),
(201, 'Current Account'),
(201, 'Credit / Prepaid Card'),
(201, 'Domestic Payments (Make payments, Accept payments)'),
(201, 'Wallet top-up - Bank Transfer'),
(201, 'Wallet top-up - Cash Deposit'),
(201, 'International Payments (Make payments, Accept payments)'),
(201, 'Bank Transfer - Wallet'),
(201, 'Bank Transfer - Cash Withdrawals'),
(201, 'Refund / Return Payments'),
(201, 'Bank Transfer - Wallet top-up'),
(201, 'Investment'),
(201, 'Domestic Payments (Make disbursements, Accept payments)'),
(201, 'International Payments (Make disbursements, Accept payments)')
;

INSERT IGNORE group_values(group_code,`value`) VALUES
(205, 'Retail Banking'),
(205, 'Business Banking (Corporate - SMEs, MSMEs, Sole Proprietor, Partnerships)'),
(205, 'Consumer'),
(205, 'Merchants / Enterprise');

COMMIT;
